

package wsclientgenerator;

import java.util.*;
import java.io.Serializable;
import de.hybris.platform.util.*;
import de.hybris.platform.core.*;
import de.hybris.platform.jalo.JaloBusinessException;
import de.hybris.platform.jalo.type.*;
import de.hybris.platform.persistence.type.*;
import de.hybris.platform.persistence.enumeration.*;
import de.hybris.platform.persistence.property.PersistenceManager;
import de.hybris.platform.persistence.*;

/**
 * Generated by hybris Platform.
 */
@SuppressWarnings({"cast","unused","boxing","null", "PMD"})
public class GeneratedTypeInitializer extends AbstractTypeInitializer
{
	/**
	 * Generated by hybris Platform.
	 */
	public GeneratedTypeInitializer( ManagerEJB manager, Map params )
	{
		super( manager, params );
	}


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected void performRemoveObjects( ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// no-op by now
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateTypes
	
	
		createItemType(
			"WebServiceConfiguration",
			"GenericItem",
			de.hybris.platform.addons.wsclientgenerator.jalo.WebServiceConfiguration.class,
			null,
			false,
			null,
			true
		);
	
		createItemType(
			"WebServiceParameter",
			"GenericItem",
			de.hybris.platform.addons.wsclientgenerator.jalo.WebServiceParameter.class,
			null,
			false,
			null,
			true
		);
	
		createItemType(
			"PersoWSParam",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.PersoWSParam.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"PriceWebServiceParameter",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.PriceWebServiceParameter.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"OrderWebServiceParameter",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.OrderWebServiceParameter.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"StockWebServiceParameter",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.StockWebServiceParameter.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"CustomerWebServiceParameter",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.CustomerWebServiceParameter.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"PriceWebServiceConfiguration",
			"WebServiceConfiguration",
			de.hybris.platform.addons.wsclientgenerator.jalo.PriceWebServiceConfiguration.class,
			"de.hybris.platform.persistence.wsclientgenerator_PriceWebServiceConfiguration",
			false,
			null,
			false
		);
	
		createItemType(
			"StockWebServiceConfiguration",
			"WebServiceConfiguration",
			de.hybris.platform.addons.wsclientgenerator.jalo.StockWebServiceConfiguration.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"OrderWebServiceConfiguration",
			"WebServiceConfiguration",
			de.hybris.platform.addons.wsclientgenerator.jalo.OrderWebServiceConfiguration.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"CustomerWebServiceConfiguration",
			"WebServiceConfiguration",
			de.hybris.platform.addons.wsclientgenerator.jalo.CustomerWebServiceConfiguration.class,
			null,
			false,
			null,
			false
		);
	
		createRelationType(
			"WebServiceConfigurationParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"WebServiceConfigurationSecurityParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"PriceWebServiceConfigurationParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"OrderWebServiceConfigurationParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"StockWebServiceConfigurationParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"CustomerWebServiceConfigurationParameterRelation",
			null,
			true
		);
	
		createEnumerationType(
			"RequestType",
			null
		);
	
		createEnumerationType(
			"ResponseType",
			null
		);
	
		createEnumerationType(
			"MethodType",
			null
		);
	
		createEnumerationType(
			"PriceParameter",
			null
		);
	
		createEnumerationType(
			"OrderParameter",
			null
		);
	
		createEnumerationType(
			"StockParameter",
			null
		);
	
		createEnumerationType(
			"CustomerParameter",
			null
		);
	
		createEnumerationType(
			"ModeType",
			null
		);
	
		createEnumerationType(
			"OrderType",
			null
		);
	
		createCollectionType(
			"PriceWSParam",
			"PriceParameter",
			CollectionType.LIST
		);
	
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performModifyTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performModifyTypes
	

	
	
				single_createattr_WebServiceConfiguration_name();
			
				single_createattr_WebServiceConfiguration_description();
			
				single_createattr_WebServiceConfiguration_url();
			
				single_createattr_WebServiceConfiguration_method();
			
				single_createattr_WebServiceConfiguration_mode();
			
				single_createattr_WebServiceConfiguration_order();
			
				single_createattr_WebServiceConfiguration_enable();
			
				single_createattr_WebServiceConfiguration_accept();
			
				single_createattr_WebServiceConfiguration_contentType();
			
				single_createattr_WebServiceConfiguration_responseTemplate();
			
				single_createattr_WebServiceConfiguration_textSeperator();
			
				single_createattr_WebServiceParameter_key();
			
				single_createattr_PersoWSParam_value();
			
				single_createattr_PriceWebServiceParameter_value();
			
				single_createattr_OrderWebServiceParameter_value();
			
				single_createattr_StockWebServiceParameter_value();
			
				single_createattr_CustomerWebServiceParameter_value();
			
				single_createattr_PriceWebServiceConfiguration_priceKey();
			
				single_createattr_PriceWebServiceConfiguration_currencyKey();
			
				single_createattr_StockWebServiceConfiguration_stockKey();
			
				single_createattr_CustomerWebServiceConfiguration_firstNameKey();
			
				single_createattr_CustomerWebServiceConfiguration_lastNameKey();
			
				single_createattr_CustomerWebServiceConfiguration_emailKey();
			
				single_createattr_CustomerWebServiceConfiguration_titleKey();
			
		createRelationAttributes(
			"WebServiceConfigurationParameterRelation", 
			false, 

			"configuration", 
			"WebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"personalisedParameters", 
			"PersoWSParam", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"WebServiceConfigurationSecurityParameterRelation", 
			false, 

			"configuration", 
			"WebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"SecurityParameters", 
			"PersoWSParam", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"PriceWebServiceConfigurationParameterRelation", 
			false, 

			"configuration", 
			"PriceWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"parameters", 
			"PriceWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"OrderWebServiceConfigurationParameterRelation", 
			false, 

			"configuration", 
			"OrderWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"parameters", 
			"OrderWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"StockWebServiceConfigurationParameterRelation", 
			false, 

			"configuration", 
			"StockWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"parameters", 
			"StockWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"CustomerWebServiceConfigurationParameterRelation", 
			false, 

			"configuration", 
			"CustomerWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"parameters", 
			"CustomerWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	

	}

	
	public void single_createattr_WebServiceConfiguration_name() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"name",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_description() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"description",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_url() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"url",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_method() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"method",  
					null,
					"MethodType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_mode() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"mode",  
					null,
					"ModeType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_order() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"order",  
					null,
					"OrderType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_enable() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"enable",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_accept() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"accept",  
					null,
					"ResponseType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_contentType() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"contentType",  
					null,
					"RequestType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_responseTemplate() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"responseTemplate",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_textSeperator() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"textSeperator",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceParameter_key() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceParameter", 
					"key",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PersoWSParam_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PersoWSParam", 
					"value",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PriceWebServiceParameter_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PriceWebServiceParameter", 
					"value",  
					null,
					"PriceParameter",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_OrderWebServiceParameter_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"OrderWebServiceParameter", 
					"value",  
					null,
					"OrderParameter",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_StockWebServiceParameter_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"StockWebServiceParameter", 
					"value",  
					null,
					"StockParameter",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerWebServiceParameter_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerWebServiceParameter", 
					"value",  
					null,
					"CustomerParameter",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PriceWebServiceConfiguration_priceKey() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PriceWebServiceConfiguration", 
					"priceKey",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PriceWebServiceConfiguration_currencyKey() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PriceWebServiceConfiguration", 
					"currencyKey",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_StockWebServiceConfiguration_stockKey() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"StockWebServiceConfiguration", 
					"stockKey",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerWebServiceConfiguration_firstNameKey() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerWebServiceConfiguration", 
					"firstNameKey",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerWebServiceConfiguration_lastNameKey() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerWebServiceConfiguration", 
					"lastNameKey",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerWebServiceConfiguration_emailKey() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerWebServiceConfiguration", 
					"emailKey",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerWebServiceConfiguration_titleKey() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerWebServiceConfiguration", 
					"titleKey",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateObjects( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateObjects
	
	
		createEnumerationValues(
			"RequestType",
			true,
			Arrays.asList( new String[] {
			
				"json",
				"xml",
				"form"
			} )
		);
	
		createEnumerationValues(
			"ResponseType",
			true,
			Arrays.asList( new String[] {
			
				"json",
				"xml",
				"text"
			} )
		);
	
		createEnumerationValues(
			"MethodType",
			true,
			Arrays.asList( new String[] {
			
				"get",
				"post"
			} )
		);
	
		createEnumerationValues(
			"PriceParameter",
			true,
			Arrays.asList( new String[] {
			
				"clientCode",
				"productCode",
				"categorieCode"
			} )
		);
	
		createEnumerationValues(
			"OrderParameter",
			true,
			Arrays.asList( new String[] {
			
				"clientCode",
				"orderCode",
				"orderStatus"
			} )
		);
	
		createEnumerationValues(
			"StockParameter",
			true,
			Arrays.asList( new String[] {
			
				"productCode",
				"clientCode"
			} )
		);
	
		createEnumerationValues(
			"CustomerParameter",
			true,
			Arrays.asList( new String[] {
			
				"clientCode",
				"clientFirstName",
				"clientLastName",
				"clientEmail",
				"titleCode"
			} )
		);
	
		createEnumerationValues(
			"ModeType",
			true,
			Arrays.asList( new String[] {
			
				"onlyWithWebService",
				"webServiceWithNative"
			} )
		);
	
		createEnumerationValues(
			"OrderType",
			true,
			Arrays.asList( new String[] {
			
				"webServiceNative",
				"NativeWebService"
			} )
		);
	
		single_setRelAttributeProperties_WebServiceConfigurationParameterRelation_source();
	
		single_setRelAttributeProperties_WebServiceConfigurationSecurityParameterRelation_source();
	
		single_setRelAttributeProperties_PriceWebServiceConfigurationParameterRelation_source();
	
		single_setRelAttributeProperties_OrderWebServiceConfigurationParameterRelation_source();
	
		single_setRelAttributeProperties_StockWebServiceConfigurationParameterRelation_source();
	
		single_setRelAttributeProperties_CustomerWebServiceConfigurationParameterRelation_source();
	
		single_setRelAttributeProperties_WebServiceConfigurationParameterRelation_target();
	
		single_setRelAttributeProperties_WebServiceConfigurationSecurityParameterRelation_target();
	
		single_setRelAttributeProperties_PriceWebServiceConfigurationParameterRelation_target();
	
		single_setRelAttributeProperties_OrderWebServiceConfigurationParameterRelation_target();
	
		single_setRelAttributeProperties_StockWebServiceConfigurationParameterRelation_target();
	
		single_setRelAttributeProperties_CustomerWebServiceConfigurationParameterRelation_target();
	
		connectRelation(
			"WebServiceConfigurationParameterRelation", 
			false, 
			"configuration", 
			"WebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"personalisedParameters", 
			"PersoWSParam", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"WebServiceConfigurationSecurityParameterRelation", 
			false, 
			"configuration", 
			"WebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"SecurityParameters", 
			"PersoWSParam", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"PriceWebServiceConfigurationParameterRelation", 
			false, 
			"configuration", 
			"PriceWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"parameters", 
			"PriceWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"OrderWebServiceConfigurationParameterRelation", 
			false, 
			"configuration", 
			"OrderWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"parameters", 
			"OrderWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"StockWebServiceConfigurationParameterRelation", 
			false, 
			"configuration", 
			"StockWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"parameters", 
			"StockWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"CustomerWebServiceConfigurationParameterRelation", 
			false, 
			"configuration", 
			"CustomerWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"parameters", 
			"CustomerWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"WebServiceConfiguration",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_WebServiceConfiguration_name();
		
			single_setAttributeProperties_WebServiceConfiguration_description();
		
			single_setAttributeProperties_WebServiceConfiguration_url();
		
			single_setAttributeProperties_WebServiceConfiguration_method();
		
			single_setAttributeProperties_WebServiceConfiguration_mode();
		
			single_setAttributeProperties_WebServiceConfiguration_order();
		
			single_setAttributeProperties_WebServiceConfiguration_enable();
		
			single_setAttributeProperties_WebServiceConfiguration_accept();
		
			single_setAttributeProperties_WebServiceConfiguration_contentType();
		
			single_setAttributeProperties_WebServiceConfiguration_responseTemplate();
		
			single_setAttributeProperties_WebServiceConfiguration_textSeperator();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"WebServiceParameter",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_WebServiceParameter_key();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PersoWSParam",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_PersoWSParam_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PriceWebServiceParameter",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_PriceWebServiceParameter_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"OrderWebServiceParameter",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_OrderWebServiceParameter_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"StockWebServiceParameter",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_StockWebServiceParameter_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"CustomerWebServiceParameter",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_CustomerWebServiceParameter_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PriceWebServiceConfiguration",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_PriceWebServiceConfiguration_priceKey();
		
			single_setAttributeProperties_PriceWebServiceConfiguration_currencyKey();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"StockWebServiceConfiguration",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_StockWebServiceConfiguration_stockKey();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"OrderWebServiceConfiguration",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"CustomerWebServiceConfiguration",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_CustomerWebServiceConfiguration_firstNameKey();
		
			single_setAttributeProperties_CustomerWebServiceConfiguration_lastNameKey();
		
			single_setAttributeProperties_CustomerWebServiceConfiguration_emailKey();
		
			single_setAttributeProperties_CustomerWebServiceConfiguration_titleKey();
		
				setDefaultProperties(
					"PriceWSParam",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"RequestType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"ResponseType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"MethodType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"PriceParameter",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"OrderParameter",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"StockParameter",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"CustomerParameter",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"ModeType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"OrderType",
					true,
					true,
					null
				);
			
	}


		
						public void single_setAttributeProperties_WebServiceConfiguration_name() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"name",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_description() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"description",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_url() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"url",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_method() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"method",
								false, 
								em().getEnumerationValue("MethodType","get"),
								"em().getEnumerationValue(\"MethodType\",\"get\")",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_mode() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"mode",
								false, 
								em().getEnumerationValue("ModeType","onlyWithWebService"),
								"em().getEnumerationValue(\"ModeType\",\"onlyWithWebService\")",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_order() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"order",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_enable() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"enable",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_accept() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"accept",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_contentType() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"contentType",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_responseTemplate() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"responseTemplate",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_textSeperator() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"textSeperator",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceParameter_key() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceParameter", 
								"key",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PersoWSParam_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PersoWSParam", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PriceWebServiceParameter_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PriceWebServiceParameter", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_OrderWebServiceParameter_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"OrderWebServiceParameter", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_StockWebServiceParameter_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"StockWebServiceParameter", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerWebServiceParameter_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerWebServiceParameter", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PriceWebServiceConfiguration_priceKey() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PriceWebServiceConfiguration", 
								"priceKey",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PriceWebServiceConfiguration_currencyKey() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PriceWebServiceConfiguration", 
								"currencyKey",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_StockWebServiceConfiguration_stockKey() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"StockWebServiceConfiguration", 
								"stockKey",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerWebServiceConfiguration_firstNameKey() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerWebServiceConfiguration", 
								"firstNameKey",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerWebServiceConfiguration_lastNameKey() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerWebServiceConfiguration", 
								"lastNameKey",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerWebServiceConfiguration_emailKey() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerWebServiceConfiguration", 
								"emailKey",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerWebServiceConfiguration_titleKey() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerWebServiceConfiguration", 
								"titleKey",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
								public void single_setRelAttributeProperties_WebServiceConfigurationParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"PersoWSParam", 
										"configuration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_WebServiceConfigurationParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"WebServiceConfiguration", 
										"personalisedParameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_WebServiceConfigurationSecurityParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"PersoWSParam", 
										"configuration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_WebServiceConfigurationSecurityParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"WebServiceConfiguration", 
										"SecurityParameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_PriceWebServiceConfigurationParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"PriceWebServiceParameter", 
										"configuration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_PriceWebServiceConfigurationParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"PriceWebServiceConfiguration", 
										"parameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_OrderWebServiceConfigurationParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"OrderWebServiceParameter", 
										"configuration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_OrderWebServiceConfigurationParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"OrderWebServiceConfiguration", 
										"parameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_StockWebServiceConfigurationParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"StockWebServiceParameter", 
										"configuration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_StockWebServiceConfigurationParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"StockWebServiceConfiguration", 
										"parameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_CustomerWebServiceConfigurationParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"CustomerWebServiceParameter", 
										"configuration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_CustomerWebServiceConfigurationParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"CustomerWebServiceConfiguration", 
										"parameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
}

	