

package wsclientgenerator;

import java.util.*;
import java.io.Serializable;
import de.hybris.platform.util.*;
import de.hybris.platform.core.*;
import de.hybris.platform.jalo.JaloBusinessException;
import de.hybris.platform.jalo.type.*;
import de.hybris.platform.persistence.type.*;
import de.hybris.platform.persistence.enumeration.*;
import de.hybris.platform.persistence.property.PersistenceManager;
import de.hybris.platform.persistence.*;

/**
 * Generated by hybris Platform.
 */
@SuppressWarnings({"cast","unused","boxing","null", "PMD"})
public class GeneratedTypeInitializer extends AbstractTypeInitializer
{
	/**
	 * Generated by hybris Platform.
	 */
	public GeneratedTypeInitializer( ManagerEJB manager, Map params )
	{
		super( manager, params );
	}


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected void performRemoveObjects( ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// no-op by now
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateTypes
	
	
		createItemType(
			"WebServiceConfiguration",
			"GenericItem",
			de.hybris.platform.addons.wsclientgenerator.jalo.WebServiceConfiguration.class,
			null,
			false,
			null,
			true
		);
	
		createItemType(
			"WebServiceParameter",
			"GenericItem",
			de.hybris.platform.addons.wsclientgenerator.jalo.WebServiceParameter.class,
			null,
			false,
			null,
			true
		);
	
		createItemType(
			"PersoWSParam",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.PersoWSParam.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"HeaderWSParam",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.HeaderWSParam.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"PriceWebServiceParameter",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.PriceWebServiceParameter.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"OrderWebServiceParameter",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.OrderWebServiceParameter.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"StockWebServiceParameter",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.StockWebServiceParameter.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"CustomerWebServiceParameter",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.CustomerWebServiceParameter.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"CustomerWebServiceResponse",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.CustomerWebServiceResponse.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"PriceWebServiceResponse",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.PriceWebServiceResponse.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"StockWebServiceResponse",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.StockWebServiceResponse.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"OrderWebServiceResponse",
			"WebServiceParameter",
			de.hybris.platform.addons.wsclientgenerator.jalo.OrderWebServiceResponse.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"PriceWebServiceConfiguration",
			"WebServiceConfiguration",
			de.hybris.platform.addons.wsclientgenerator.jalo.PriceWebServiceConfiguration.class,
			"de.hybris.platform.persistence.wsclientgenerator_PriceWebServiceConfiguration",
			false,
			null,
			false
		);
	
		createItemType(
			"StockWebServiceConfiguration",
			"WebServiceConfiguration",
			de.hybris.platform.addons.wsclientgenerator.jalo.StockWebServiceConfiguration.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"OrderWebServiceConfiguration",
			"WebServiceConfiguration",
			de.hybris.platform.addons.wsclientgenerator.jalo.OrderWebServiceConfiguration.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"CustomerWebServiceConfiguration",
			"WebServiceConfiguration",
			de.hybris.platform.addons.wsclientgenerator.jalo.CustomerWebServiceConfiguration.class,
			null,
			false,
			null,
			false
		);
	
		createRelationType(
			"WebServiceConfigurationParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"WebServiceConfigurationHeadersParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"PriceWebServiceConfigurationParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"OrderWebServiceConfigurationParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"StockWebServiceConfigurationParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"CustomerWebServiceConfigurationParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"PriceWebServiceConfigurationHeaderParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"OrderWebServiceConfigurationHeaderParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"StockWebServiceConfigurationHeaderParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"CustomerWebServiceConfigurationHeaderParameterRelation",
			null,
			true
		);
	
		createRelationType(
			"CustomerWebServiceConfigurationResponseMappingrRelation",
			null,
			true
		);
	
		createRelationType(
			"PriceWebServiceConfigurationResponseMappingrRelation",
			null,
			true
		);
	
		createRelationType(
			"StockWebServiceConfigurationResponseMappingrRelation",
			null,
			true
		);
	
		createRelationType(
			"OrderWebServiceConfigurationResponseMappingrRelation",
			null,
			true
		);
	
		createEnumerationType(
			"RequestType",
			null
		);
	
		createEnumerationType(
			"ResponseType",
			null
		);
	
		createEnumerationType(
			"MethodType",
			null
		);
	
		createEnumerationType(
			"PriceParameter",
			null
		);
	
		createEnumerationType(
			"OrderParameter",
			null
		);
	
		createEnumerationType(
			"StockParameter",
			null
		);
	
		createEnumerationType(
			"CustomerParameter",
			null
		);
	
		createEnumerationType(
			"ModeType",
			null
		);
	
		createEnumerationType(
			"CustomerMappingResponse",
			null
		);
	
		createEnumerationType(
			"PriceMappingResponse",
			null
		);
	
		createEnumerationType(
			"StockMappingResponse",
			null
		);
	
		createEnumerationType(
			"OrderMappingResponse",
			null
		);
	
		createCollectionType(
			"PriceWSParam",
			"PriceParameter",
			CollectionType.LIST
		);
	
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performModifyTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performModifyTypes
	

	
	
				single_createattr_WebServiceConfiguration_name();
			
				single_createattr_WebServiceConfiguration_description();
			
				single_createattr_WebServiceConfiguration_url();
			
				single_createattr_WebServiceConfiguration_method();
			
				single_createattr_WebServiceConfiguration_mode();
			
				single_createattr_WebServiceConfiguration_enable();
			
				single_createattr_WebServiceConfiguration_accept();
			
				single_createattr_WebServiceConfiguration_contentType();
			
				single_createattr_WebServiceConfiguration_responseTemplate();
			
				single_createattr_WebServiceConfiguration_textSeperator();
			
				single_createattr_WebServiceConfiguration_rootKey();
			
				single_createattr_WebServiceConfiguration_login();
			
				single_createattr_WebServiceConfiguration_password();
			
				single_createattr_WebServiceConfiguration_successCode();
			
				single_createattr_WebServiceParameter_key();
			
				single_createattr_PersoWSParam_value();
			
				single_createattr_HeaderWSParam_value();
			
				single_createattr_PriceWebServiceParameter_value();
			
				single_createattr_OrderWebServiceParameter_value();
			
				single_createattr_StockWebServiceParameter_value();
			
				single_createattr_CustomerWebServiceParameter_value();
			
				single_createattr_CustomerWebServiceResponse_value();
			
				single_createattr_PriceWebServiceResponse_value();
			
				single_createattr_StockWebServiceResponse_value();
			
				single_createattr_OrderWebServiceResponse_value();
			
		createRelationAttributes(
			"WebServiceConfigurationParameterRelation", 
			false, 

			"configuration", 
			"WebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"personalisedParameters", 
			"PersoWSParam", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"WebServiceConfigurationHeadersParameterRelation", 
			false, 

			"configurationHeader", 
			"WebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"headersParameters", 
			"HeaderWSParam", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"PriceWebServiceConfigurationParameterRelation", 
			false, 

			"configuration", 
			"PriceWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"parameters", 
			"PriceWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"OrderWebServiceConfigurationParameterRelation", 
			false, 

			"configuration", 
			"OrderWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"parameters", 
			"OrderWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"StockWebServiceConfigurationParameterRelation", 
			false, 

			"configuration", 
			"StockWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"parameters", 
			"StockWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"CustomerWebServiceConfigurationParameterRelation", 
			false, 

			"configuration", 
			"CustomerWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"parameters", 
			"CustomerWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"PriceWebServiceConfigurationHeaderParameterRelation", 
			false, 

			"priceConfiguration", 
			"PriceWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"pathParameters", 
			"PriceWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"OrderWebServiceConfigurationHeaderParameterRelation", 
			false, 

			"orderConfiguration", 
			"OrderWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"pathParameters", 
			"OrderWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"StockWebServiceConfigurationHeaderParameterRelation", 
			false, 

			"stockConfiguration", 
			"StockWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"pathParameters", 
			"StockWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"CustomerWebServiceConfigurationHeaderParameterRelation", 
			false, 

			"customerConfiguration", 
			"CustomerWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"pathParameters", 
			"CustomerWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"CustomerWebServiceConfigurationResponseMappingrRelation", 
			false, 

			"customerConfiguration", 
			"CustomerWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"responseMapping", 
			"CustomerWebServiceResponse", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"PriceWebServiceConfigurationResponseMappingrRelation", 
			false, 

			"customerConfiguration", 
			"PriceWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"responseMapping", 
			"PriceWebServiceResponse", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"StockWebServiceConfigurationResponseMappingrRelation", 
			false, 

			"customerConfiguration", 
			"StockWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"responseMapping", 
			"StockWebServiceResponse", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	
		createRelationAttributes(
			"OrderWebServiceConfigurationResponseMappingrRelation", 
			false, 

			"customerConfiguration", 
			"OrderWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			false,
			false,
			CollectionType.COLLECTION,
			"responseMapping", 
			"OrderWebServiceResponse", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			false,
			CollectionType.COLLECTION
		);
	

	}

	
	public void single_createattr_WebServiceConfiguration_name() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"name",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_description() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"description",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_url() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"url",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_method() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"method",  
					null,
					"MethodType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_mode() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"mode",  
					null,
					"ModeType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_enable() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"enable",  
					null,
					"java.lang.Boolean",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_accept() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"accept",  
					null,
					"ResponseType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_contentType() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"contentType",  
					null,
					"RequestType",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_responseTemplate() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"responseTemplate",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_textSeperator() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"textSeperator",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_rootKey() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"rootKey",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_login() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"login",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_password() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"password",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceConfiguration_successCode() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceConfiguration", 
					"successCode",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_WebServiceParameter_key() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"WebServiceParameter", 
					"key",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PersoWSParam_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PersoWSParam", 
					"value",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_HeaderWSParam_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"HeaderWSParam", 
					"value",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PriceWebServiceParameter_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PriceWebServiceParameter", 
					"value",  
					null,
					"PriceParameter",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_OrderWebServiceParameter_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"OrderWebServiceParameter", 
					"value",  
					null,
					"OrderParameter",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_StockWebServiceParameter_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"StockWebServiceParameter", 
					"value",  
					null,
					"StockParameter",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerWebServiceParameter_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerWebServiceParameter", 
					"value",  
					null,
					"CustomerParameter",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerWebServiceResponse_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerWebServiceResponse", 
					"value",  
					null,
					"CustomerMappingResponse",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PriceWebServiceResponse_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PriceWebServiceResponse", 
					"value",  
					null,
					"PriceMappingResponse",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_StockWebServiceResponse_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"StockWebServiceResponse", 
					"value",  
					null,
					"StockMappingResponse",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_OrderWebServiceResponse_value() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"OrderWebServiceResponse", 
					"value",  
					null,
					"OrderMappingResponse",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateObjects( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateObjects
	
	
		createEnumerationValues(
			"RequestType",
			true,
			Arrays.asList( new String[] {
			
				"json",
				"xml",
				"form"
			} )
		);
	
		createEnumerationValues(
			"ResponseType",
			true,
			Arrays.asList( new String[] {
			
				"json",
				"xml"
			} )
		);
	
		createEnumerationValues(
			"MethodType",
			true,
			Arrays.asList( new String[] {
			
				"get",
				"post",
				"put",
				"delete"
			} )
		);
	
		createEnumerationValues(
			"PriceParameter",
			true,
			Arrays.asList( new String[] {
			
				"uid",
				"code",
				"supercategories"
			} )
		);
	
		createEnumerationValues(
			"OrderParameter",
			true,
			Arrays.asList( new String[] {
			
				"uid",
				"code",
				"date"
			} )
		);
	
		createEnumerationValues(
			"StockParameter",
			true,
			Arrays.asList( new String[] {
			
				"code",
				"uid",
				"orderCode",
				"stockValue"
			} )
		);
	
		createEnumerationValues(
			"CustomerParameter",
			true,
			Arrays.asList( new String[] {
			
				"uid",
				"firstName",
				"lastName",
				"oldEmail",
				"newEmail",
				"titleCode"
			} )
		);
	
		createEnumerationValues(
			"ModeType",
			true,
			Arrays.asList( new String[] {
			
				"onlyWithWebService",
				"webServiceNative",
				"NativeWebService"
			} )
		);
	
		createEnumerationValues(
			"CustomerMappingResponse",
			true,
			Arrays.asList( new String[] {
			
				"uid",
				"firstName",
				"lastName",
				"titleCode",
				"successCode"
			} )
		);
	
		createEnumerationValues(
			"PriceMappingResponse",
			true,
			Arrays.asList( new String[] {
			
				"price",
				"currency",
				"successCode"
			} )
		);
	
		createEnumerationValues(
			"StockMappingResponse",
			true,
			Arrays.asList( new String[] {
			
				"stockValue",
				"successCode"
			} )
		);
	
		createEnumerationValues(
			"OrderMappingResponse",
			true,
			Arrays.asList( new String[] {
			
				"status",
				"successCode"
			} )
		);
	
		single_setRelAttributeProperties_WebServiceConfigurationParameterRelation_source();
	
		single_setRelAttributeProperties_WebServiceConfigurationHeadersParameterRelation_source();
	
		single_setRelAttributeProperties_PriceWebServiceConfigurationParameterRelation_source();
	
		single_setRelAttributeProperties_OrderWebServiceConfigurationParameterRelation_source();
	
		single_setRelAttributeProperties_StockWebServiceConfigurationParameterRelation_source();
	
		single_setRelAttributeProperties_CustomerWebServiceConfigurationParameterRelation_source();
	
		single_setRelAttributeProperties_PriceWebServiceConfigurationHeaderParameterRelation_source();
	
		single_setRelAttributeProperties_OrderWebServiceConfigurationHeaderParameterRelation_source();
	
		single_setRelAttributeProperties_StockWebServiceConfigurationHeaderParameterRelation_source();
	
		single_setRelAttributeProperties_CustomerWebServiceConfigurationHeaderParameterRelation_source();
	
		single_setRelAttributeProperties_CustomerWebServiceConfigurationResponseMappingrRelation_source();
	
		single_setRelAttributeProperties_PriceWebServiceConfigurationResponseMappingrRelation_source();
	
		single_setRelAttributeProperties_StockWebServiceConfigurationResponseMappingrRelation_source();
	
		single_setRelAttributeProperties_OrderWebServiceConfigurationResponseMappingrRelation_source();
	
		single_setRelAttributeProperties_WebServiceConfigurationParameterRelation_target();
	
		single_setRelAttributeProperties_WebServiceConfigurationHeadersParameterRelation_target();
	
		single_setRelAttributeProperties_PriceWebServiceConfigurationParameterRelation_target();
	
		single_setRelAttributeProperties_OrderWebServiceConfigurationParameterRelation_target();
	
		single_setRelAttributeProperties_StockWebServiceConfigurationParameterRelation_target();
	
		single_setRelAttributeProperties_CustomerWebServiceConfigurationParameterRelation_target();
	
		single_setRelAttributeProperties_PriceWebServiceConfigurationHeaderParameterRelation_target();
	
		single_setRelAttributeProperties_OrderWebServiceConfigurationHeaderParameterRelation_target();
	
		single_setRelAttributeProperties_StockWebServiceConfigurationHeaderParameterRelation_target();
	
		single_setRelAttributeProperties_CustomerWebServiceConfigurationHeaderParameterRelation_target();
	
		single_setRelAttributeProperties_CustomerWebServiceConfigurationResponseMappingrRelation_target();
	
		single_setRelAttributeProperties_PriceWebServiceConfigurationResponseMappingrRelation_target();
	
		single_setRelAttributeProperties_StockWebServiceConfigurationResponseMappingrRelation_target();
	
		single_setRelAttributeProperties_OrderWebServiceConfigurationResponseMappingrRelation_target();
	
		connectRelation(
			"WebServiceConfigurationParameterRelation", 
			false, 
			"configuration", 
			"WebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"personalisedParameters", 
			"PersoWSParam", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"WebServiceConfigurationHeadersParameterRelation", 
			false, 
			"configurationHeader", 
			"WebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"headersParameters", 
			"HeaderWSParam", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"PriceWebServiceConfigurationParameterRelation", 
			false, 
			"configuration", 
			"PriceWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"parameters", 
			"PriceWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"OrderWebServiceConfigurationParameterRelation", 
			false, 
			"configuration", 
			"OrderWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"parameters", 
			"OrderWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"StockWebServiceConfigurationParameterRelation", 
			false, 
			"configuration", 
			"StockWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"parameters", 
			"StockWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"CustomerWebServiceConfigurationParameterRelation", 
			false, 
			"configuration", 
			"CustomerWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"parameters", 
			"CustomerWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"PriceWebServiceConfigurationHeaderParameterRelation", 
			false, 
			"priceConfiguration", 
			"PriceWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"pathParameters", 
			"PriceWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"OrderWebServiceConfigurationHeaderParameterRelation", 
			false, 
			"orderConfiguration", 
			"OrderWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"pathParameters", 
			"OrderWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"StockWebServiceConfigurationHeaderParameterRelation", 
			false, 
			"stockConfiguration", 
			"StockWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"pathParameters", 
			"StockWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"CustomerWebServiceConfigurationHeaderParameterRelation", 
			false, 
			"customerConfiguration", 
			"CustomerWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"pathParameters", 
			"CustomerWebServiceParameter", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"CustomerWebServiceConfigurationResponseMappingrRelation", 
			false, 
			"customerConfiguration", 
			"CustomerWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"responseMapping", 
			"CustomerWebServiceResponse", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"PriceWebServiceConfigurationResponseMappingrRelation", 
			false, 
			"customerConfiguration", 
			"PriceWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"responseMapping", 
			"PriceWebServiceResponse", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"StockWebServiceConfigurationResponseMappingrRelation", 
			false, 
			"customerConfiguration", 
			"StockWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"responseMapping", 
			"StockWebServiceResponse", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
		connectRelation(
			"OrderWebServiceConfigurationResponseMappingrRelation", 
			false, 
			"customerConfiguration", 
			"OrderWebServiceConfiguration", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"responseMapping", 
			"OrderWebServiceResponse", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"WebServiceConfiguration",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_WebServiceConfiguration_name();
		
			single_setAttributeProperties_WebServiceConfiguration_description();
		
			single_setAttributeProperties_WebServiceConfiguration_url();
		
			single_setAttributeProperties_WebServiceConfiguration_method();
		
			single_setAttributeProperties_WebServiceConfiguration_mode();
		
			single_setAttributeProperties_WebServiceConfiguration_enable();
		
			single_setAttributeProperties_WebServiceConfiguration_accept();
		
			single_setAttributeProperties_WebServiceConfiguration_contentType();
		
			single_setAttributeProperties_WebServiceConfiguration_responseTemplate();
		
			single_setAttributeProperties_WebServiceConfiguration_textSeperator();
		
			single_setAttributeProperties_WebServiceConfiguration_rootKey();
		
			single_setAttributeProperties_WebServiceConfiguration_login();
		
			single_setAttributeProperties_WebServiceConfiguration_password();
		
			single_setAttributeProperties_WebServiceConfiguration_successCode();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"WebServiceParameter",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_WebServiceParameter_key();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PersoWSParam",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_PersoWSParam_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"HeaderWSParam",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_HeaderWSParam_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PriceWebServiceParameter",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_PriceWebServiceParameter_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"OrderWebServiceParameter",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_OrderWebServiceParameter_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"StockWebServiceParameter",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_StockWebServiceParameter_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"CustomerWebServiceParameter",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_CustomerWebServiceParameter_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"CustomerWebServiceResponse",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_CustomerWebServiceResponse_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PriceWebServiceResponse",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_PriceWebServiceResponse_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"StockWebServiceResponse",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_StockWebServiceResponse_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"OrderWebServiceResponse",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_OrderWebServiceResponse_value();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PriceWebServiceConfiguration",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"StockWebServiceConfiguration",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"OrderWebServiceConfiguration",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"CustomerWebServiceConfiguration",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				setDefaultProperties(
					"PriceWSParam",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"RequestType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"ResponseType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"MethodType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"PriceParameter",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"OrderParameter",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"StockParameter",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"CustomerParameter",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"ModeType",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"CustomerMappingResponse",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"PriceMappingResponse",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"StockMappingResponse",
					true,
					true,
					null
				);
			
				setDefaultProperties(
					"OrderMappingResponse",
					true,
					true,
					null
				);
			
	}


		
						public void single_setAttributeProperties_WebServiceConfiguration_name() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"name",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_description() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"description",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_url() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"url",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_method() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"method",
								false, 
								em().getEnumerationValue("MethodType","get"),
								"em().getEnumerationValue(\"MethodType\",\"get\")",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_mode() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"mode",
								false, 
								em().getEnumerationValue("ModeType","onlyWithWebService"),
								"em().getEnumerationValue(\"ModeType\",\"onlyWithWebService\")",
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_enable() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"enable",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_accept() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"accept",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_contentType() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"contentType",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_responseTemplate() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"responseTemplate",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_textSeperator() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"textSeperator",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_rootKey() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"rootKey",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_login() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"login",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_password() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"password",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceConfiguration_successCode() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceConfiguration", 
								"successCode",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_WebServiceParameter_key() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"WebServiceParameter", 
								"key",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PersoWSParam_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PersoWSParam", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_HeaderWSParam_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"HeaderWSParam", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PriceWebServiceParameter_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PriceWebServiceParameter", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_OrderWebServiceParameter_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"OrderWebServiceParameter", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_StockWebServiceParameter_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"StockWebServiceParameter", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerWebServiceParameter_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerWebServiceParameter", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerWebServiceResponse_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerWebServiceResponse", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PriceWebServiceResponse_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PriceWebServiceResponse", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_StockWebServiceResponse_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"StockWebServiceResponse", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_OrderWebServiceResponse_value() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"OrderWebServiceResponse", 
								"value",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
								public void single_setRelAttributeProperties_WebServiceConfigurationParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"PersoWSParam", 
										"configuration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_WebServiceConfigurationParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"WebServiceConfiguration", 
										"personalisedParameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_WebServiceConfigurationHeadersParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"HeaderWSParam", 
										"configurationHeader",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_WebServiceConfigurationHeadersParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"WebServiceConfiguration", 
										"headersParameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_PriceWebServiceConfigurationParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"PriceWebServiceParameter", 
										"configuration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_PriceWebServiceConfigurationParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"PriceWebServiceConfiguration", 
										"parameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_OrderWebServiceConfigurationParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"OrderWebServiceParameter", 
										"configuration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_OrderWebServiceConfigurationParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"OrderWebServiceConfiguration", 
										"parameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_StockWebServiceConfigurationParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"StockWebServiceParameter", 
										"configuration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_StockWebServiceConfigurationParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"StockWebServiceConfiguration", 
										"parameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_CustomerWebServiceConfigurationParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"CustomerWebServiceParameter", 
										"configuration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_CustomerWebServiceConfigurationParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"CustomerWebServiceConfiguration", 
										"parameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_PriceWebServiceConfigurationHeaderParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"PriceWebServiceParameter", 
										"priceConfiguration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_PriceWebServiceConfigurationHeaderParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"PriceWebServiceConfiguration", 
										"pathParameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_OrderWebServiceConfigurationHeaderParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"OrderWebServiceParameter", 
										"orderConfiguration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_OrderWebServiceConfigurationHeaderParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"OrderWebServiceConfiguration", 
										"pathParameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_StockWebServiceConfigurationHeaderParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"StockWebServiceParameter", 
										"stockConfiguration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_StockWebServiceConfigurationHeaderParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"StockWebServiceConfiguration", 
										"pathParameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_CustomerWebServiceConfigurationHeaderParameterRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"CustomerWebServiceParameter", 
										"customerConfiguration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_CustomerWebServiceConfigurationHeaderParameterRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"CustomerWebServiceConfiguration", 
										"pathParameters",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_CustomerWebServiceConfigurationResponseMappingrRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"CustomerWebServiceResponse", 
										"customerConfiguration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_CustomerWebServiceConfigurationResponseMappingrRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"CustomerWebServiceConfiguration", 
										"responseMapping",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_PriceWebServiceConfigurationResponseMappingrRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"PriceWebServiceResponse", 
										"customerConfiguration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_PriceWebServiceConfigurationResponseMappingrRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"PriceWebServiceConfiguration", 
										"responseMapping",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_StockWebServiceConfigurationResponseMappingrRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"StockWebServiceResponse", 
										"customerConfiguration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_StockWebServiceConfigurationResponseMappingrRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"StockWebServiceConfiguration", 
										"responseMapping",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_OrderWebServiceConfigurationResponseMappingrRelation_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"OrderWebServiceResponse", 
										"customerConfiguration",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_OrderWebServiceConfigurationResponseMappingrRelation_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"OrderWebServiceConfiguration", 
										"responseMapping",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
}

	